- name: agente_zabbix #maquina que sera monitorada
  hosts: zabbix_server # crie um arquivo inventario.ini e coloque as informação do host
  become: yes

  vars_files:
    - variaveis.yml 
  
  tasks:

    - name: Baixar repositório do Zabbix 7.0
      ansible.builtin.dnf:
        name: "https://repo.zabbix.com/zabbix/7.0/rhel/9/x86_64/zabbix-release-latest.el9.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: Limpar cache do dnf
      ansible.builtin.command: dnf clean all

    - name: Instalar Zabbix Agent 2
      ansible.builtin.dnf:
        name: zabbix-agent2
        state: present
        disablerepo: "epel,ol9_developer_EPEL"

    - name: Configurar zabbix_agent2.conf
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?\s*Server=', line: 'Server={{ zabbix_server_ip }}' }
        - { regexp: '^#?\s*ServerActive=', line: 'ServerActive={{ zabbix_server_ip }}' }
        - { regexp: '^#?\s*Hostname=', line: 'Hostname={{ inventory_hostname }}' }
      notify: Restart zabbix-agent2

    - name: Liberar porta 10050 no firewall
      ansible.posix.firewalld:
        port: 10050/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Habilitar e iniciar Zabbix Agent 2
      ansible.builtin.service:
        name: zabbix-agent2
        state: started
        enabled: yes

  handlers:
    - name: Restart zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
